# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:26
from __future__ import unicode_literals

import core.config.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes_Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloquear_criacao', models.BooleanField(default=True, editable=False, unique=True)),
                ('titulo_pagInicial', models.CharField(default='Texto Padrão', max_length=30)),
                ('subTitulo_pagInicial', models.CharField(default='Altere-o através da interface de ADMIN', max_length=40)),
                ('elementos_rodape', models.IntegerField(default=10, max_length=2, validators=[core.config.validators.validar_quantidadeElementosRodape])),
                ('icone', models.ImageField(blank=True, upload_to='imagens/icone')),
            ],
        ),
        migrations.CreateModel(
            name='Rodape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.ImageField(blank=True, help_text='Coloque o icone no tamanho y x y', upload_to='imagens/rodape/icone')),
                ('texto', models.CharField(help_text='Texto que vai aparecer no icone', max_length=30)),
                ('link', models.URLField(blank=True, help_text='Coloque um link para redirecionar para a página')),
                ('configuracoes_Sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Configuracoes_Sistema')),
            ],
        ),
    ]
