# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Escreva o seu nome completo', max_length=50)),
                ('orientador', models.CharField(blank=True, max_length=50)),
                ('email_orientador', models.EmailField(blank=True, max_length=254)),
                ('chave_de_ativacao', models.CharField(blank=True, max_length=40, null=True)),
                ('chave_expira', models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 1, 8, 26, 0, 490797))),
            ],
            options={
                'permissions': (('view_aluno', 'can_view_aluno'),),
            },
        ),
        migrations.CreateModel(
            name='AlunoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='nome bonito para as urls', max_length=100, unique=True)),
                ('pendencia', models.BooleanField(default=True, help_text='True = Pendente a aprovação e False = Aceito na disciplina', verbose_name='Pendente')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=30)),
                ('arquivo', models.FileField(upload_to='atividades/arquivos/atividades')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('semestre', models.CharField(help_text='Ex: 2014.1', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_professor', 'can_view_professor'),),
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.Professor'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.Disciplina'),
        ),
        migrations.AddField(
            model_name='alunodisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ava.Disciplina'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, through='ava.AlunoDisciplina', to='ava.Disciplina'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário/Email'),
        ),
        migrations.AlterUniqueTogether(
            name='alunodisciplina',
            unique_together=set([('aluno', 'disciplina')]),
        ),
    ]
