# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='aluno',
            field=models.ManyToManyField(blank=True, through='core.AlunosMatriculados', to='core.Aluno'),
        ),
    ]
