# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Essa permissao da direito ao usuario manipular o que ele quiser no sistema', verbose_name='Super usuario')),
                ('email', models.EmailField(help_text='Digite o seu endereco de email ex: myemal@mail.com', max_length=70, unique=True, verbose_name='email')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Usuario esta ativo, ou seja, pode utilizar o sistema normalmente.', verbose_name='ativo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criacao da conta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of his/her group.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissoes especificas do usuario', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='permissoes de usuario')),
            ],
            options={
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
                'verbose_name_plural': 'usuarios',
                'verbose_name': 'usuario',
            },
        ),
    ]
